name: general-tests

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/bbb-yocto.git
        lfs: true

    - name: clone docker
      run: |
        git clone https://github.com/dogusyuksel/embedded_docker.git docker
        cp -rf docker/* .

    - name: Remove unnecessary files
      run: |
        ./free_space.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: prepare build
      run: |
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master 'cd /thirdparty && source poky/oe-init-build-env'
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master 'cd /thirdparty && cp -rf /workspace/local_conf.diff build/conf && cd build/conf && patch local.conf < local_conf.diff && cat local.conf'
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master 'cd /build && bitbake-layers add-layer /workspace/meta-custom && bitbake-layers show-recipes hello'
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master 'cd /build && bitbake hello && ls -l ./tmp/deploy/rpm/cortexa8hf_neon/ | grep hello'
        echo 'RUN THIS (BUT CANNOT BECAUSE OF MEMORY) ==> cd /build && bitbake core-image-full-cmdline && find . -name "*.wic"'
