name: general-tests

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/bbb-yocto.git
        lfs: true

    - name: Download Repos
      run: |
        ./setup_environment.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: prepare build environment
      run: |
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace && source poky/oe-init-build-env"

    - name: patch conf file
      run: |
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace && echo "MACHINE ?= \"beaglebone-yocto\"" >> ./build/conf/local.conf2 && cat ./build/conf/local.conf >> ./build/conf/local.conf2 && mv -f ./build/conf/local.conf2 ./build/conf/local.conf && cat ./build/conf/local.conf"

    - name: prepare build environment
      run: |
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace && source poky/oe-init-build-env && bitbake core-image-x11 && find . -name \"*.wic\""
